"""Add phone_number to Client

Revision ID: 1b34c5336e90
Revises: dc34d4f6038f
Create Date: 2025-11-20 08:58:46.132615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b34c5336e90'
down_revision = 'dc34d4f6038f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
