"""Initial migration.

Revision ID: dc34d4f6038f
Revises:
Create Date: 2025-11-20 07:22:23.439475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc34d4f6038f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('contact_details', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)

    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=64), nullable=True),
    sa.Column('court_name', sa.String(length=128), nullable=True),
    sa.Column('case_title', sa.String(length=256), nullable=True),
    sa.Column('case_type', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('opponent_name', sa.String(length=128), nullable=True),
    sa.Column('opponent_advocate', sa.String(length=128), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('current_stage', sa.String(length=128), nullable=True),
    sa.Column('next_hearing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_case_number'), ['case_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_next_hearing_date'), ['next_hearing_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_next_hearing_date'))
        batch_op.drop_index(batch_op.f('ix_case_case_number'))

    op.drop_table('case')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_name'))

    op.drop_table('client')
    # ### end Alembic commands ###
